### ISSUE TITLE
fix: Session 생성시 해당 기수 회원의 Pending 상태인 출석 정보를 생성한다.

### ISSUE THREAD

**Issue by xxeol2** [Nexters/nexters-admin-server#55]
- Session 생성시 해당 기수 회원의 Pending 상태인 출석 정보를 생성

**Comment by bugoverdose** [comment]
Session 생성시 Pending 상태인 출석 정보를 생성하는건 어떨까요? QR 코드 생성 이전에 통보 결석을 하는 경우에 대응할 수 있을 것 같아요.
