### ISSUE TITLE
feat: 관리자 관련 회원 업무 api를 작성한다

### ISSUE THREAD

**Issue by kth990303** [Nexters/nexters-admin-server#7]
[노션 링크](https://www.notion.so/0204-API-619c65c8d7cb4cfb850ef75c6ebad1df)

## 사용 기술 스택
- Spring Data JPA (우선은 `페이지네이션 미적용`)
- Swagger (SpringDoc)

## API 목록
- 회원 전체 조회
- 회원 단건 생성
- 회원 단건 삭제 (우선은 `물리적 삭제`)
- 회원 단건 수정
  - 활동정보수정
  - 직군 수정
  - 상태 (수료, 미이수, 이수 등) 수정  

### 어드민

- 복수 회원 조회: `GET /api/members`
    - 어드민에서 회원 관리 탭을 누를 때 조회 api
    - member, generation_member 프로퍼티들 가져오면 됨.
    
    ```coffeescript
    GET /api/members
    Authorization: Bearer admin.jwt.token
    
    ResponseBody {
    		data: [{
    			id: int,
    	    name: string
    	    gender: string
    	    email: string
    			phoneNumber: string
    	    generations: [int]
    	    position: string
    	    subPosition: string
    	    status: string
    	    isManager: boolean
        }]
    }
    ```
    
- 단건 생성 `POST /api/members`
    - 회원 일괄 업로드 외에 별도로 회원 추가할 수 있도록
    
    ```coffeescript
    POST /api/members
    Authorization: Bearer admin.jwt.token
    
    RequestBody {
        name: string
        gender: string
        email: string
    		phoneNumber: string
        generations: [int]
        position: string
        subPosition: string
        status: string
        isManager: boolean
    }
    
    400 BAD REQUEST
    401 UNAUTHORIZED - 토큰 없을 때
    403 FORBIDDEN - member.jwt.token으로 요청 보냈을 때* 
    ```
    
- 회원 정보 수정 `PUT /api/members/{id}`
    - 회원 정보 수정, 활동 구분 수정, 회원 삭제 API가 다 따로 있음
    
    ```coffeescript
    PUT /api/members/{id}
    Authorization: Bearer admin.jwt.token
    
    RequestBody {
        name: string
        gender: string
        email: string
    		phoneNumber: string
        generations: [int]
        isManager: boolean
    }
    ```
    
- 활동구분 수정 `PUT /api/members/{id}/status`
    
    ```coffeescript
    PUT /api/members/{id}/position
    Authorization: Bearer admin.jwt.token
    
    RequestBody {
        status: string
    }
    ```
   
    
- 직군 수정 `PUT /api/members/{id}/position`
    
    ```coffeescript
    PUT /api/members/{id}/position
    Authorization: Bearer admin.jwt.token
    
    RequestBody {
        position: string,
        subPosition: string
    }
    ```
    
    
- 회원 삭제 `DELETE /api/members/{id}`
    - 관리자가 특정 회원을 삭제하는 api
    
    ```coffeescript
    DELETE /api/members/{id}
    Authorization: Bearer admin.jwt.token
    ```

**Comment by kth990303** [comment]
회원 단건 추가할 때, 기수 정보는 여러 개를 받지만 직군/세부직군은 최근 1개 정보만 받습니다.
이럴 경우 아래 상황에서 문제가 발생할 듯해요.

`특정 회원에 대한 이전 기수회원 정보 등록 시에 직군이 null이 저장` (이전 기수일 때 활동한 직군 정보가 있어도 말이죠.)

아래와 같이 requestBody를 바꿔야될 것 같은데 어떻게 생각하시나요?

### 단건 생성
 ```coffeescript
POST /api/members
Authorization: Bearer admin.jwt.token

RequestBody {
    name: string
    gender: string
    email: string
    phoneNumber: string
    generationInfo: [{
        generations: int
        position: string
        subPosition: string
        status: string
        isManager: Boolean
    }]
}
```

**Comment by kth990303** [comment]
회원 정보를 수정할 때, 피그마 기획 상으로는 isManager 프로퍼티에 대한 변경은 request로 받지 않는 것으로 보입니다.
![image](https://user-images.githubusercontent.com/57135043/217743940-173f267c-d82c-4683-b65e-68a4732b8304.png)

따라서 requestBody를 아래로 변경한 상태로 진행하려 합니다.

```coffeescript
PUT /api/members/{id}
Authorization: Bearer admin.jwt.token

RequestBody {
    name: string
    gender: string
    email: string
    phoneNumber: string
    generations: [int]
} 
# isManager을 뺐음.
```

**Comment by kth990303** [comment]
회원 정보를 수정할 때, 아래와 같은 경우는 어떻게 해야 할까요?

### 문제 상황
- 특정 회원이 8기 정보만 있었는데 22기 정보가 추가됨.
- 그런데 22기에서 이 회원은 A 직군이 아닌 B 직군으로 변경
  - 22기에서 이 회원이 B 직군으로 변경했다고 수정해주는 칸은 따로 없는 것 같다.
- 기수에 대한 변경은 있으나, 특정 회원의 기수가 수정될 때 수정된 기수에 대한 직군 변경은 존재하지 않는 것 같음. 

### 임시로 내린 결론 및 개발상황
따라서 **GenerationMember의 `Position`, `SubPosition`을 nullable하게 변경하려 합니다.**

**Comment by kth990303** [comment]
회원 정보 수정 시에 email도 변경이 가능한데, JwtTokenProviderTest를 보면 알 수 있듯이 사실상 이메일이 payload이자 식별자입니다.
이메일을 변경할 수 있게 하는 것이 맞을까요?

**Comment by xxeol2** [comment]
> 회원 단건 추가할 때, 기수 정보는 여러 개를 받지만 직군/세부직군은 최근 1개 정보만 받습니다. 이럴 경우 아래 상황에서 문제가 발생할 듯해요.
> 
> `특정 회원에 대한 이전 기수회원 정보 등록 시에 직군이 null이 저장` (이전 기수일 때 활동한 직군 정보가 있어도 말이죠.)

저번 회의때 해당 부분에 대해서 이전 기수에 대해서도 전부 다 동일한 직군으로 넣어주기로 얘기 나왔던걸로 기억해요!

**Comment by xxeol2** [comment]
> * 기수에 대한 변경은 있으나, 특정 회원의 기수가 수정될 때 수정된 기수에 대한 직군 변경은 존재하지 않는 것 같음.

전에 제가 오프라인에서 한 번 질문했던 것 같은데, 제가 기억하는게 맞다면...
8기 정보가 존재하는 회원, 즉 위클리 서비스에 이미 계정이 존재하는 회원의 경우는 `회원 수정 API`가 아닌 `회원 등록 API`를 통해 22기 정보가 추가될 것 같아요.
즉, 회원 등록 API 요청시 이메일값을 기준으로 이미 존재하는 회원인지 판단하고 이미 존재한다면 새로운 Member를 추가해주는게 아닌 기존 Member에 GenerationMember를 추가해주는 방식이 될 것 같아요.

`회원 수정 API`로 다른 기수를 추가해주는 경우엔.. 가장 최근 직군 따라 가는게 좋지 않을까?라는 생각이 드는데(회원 정보 조회시에 가장 최근 직군을 보여주기 때문), 함께 얘기 나눠보면 좋을 것 같아요!

**Comment by xxeol2** [comment]
> 회원 정보를 수정할 때, 아래와 같은 경우는 어떻게 해야 할까요?
> 
> ### 문제 상황
> * 특정 회원이 8기 정보만 있었는데 22기 정보가 추가됨.
> * 그런데 22기에서 이 회원은 A 직군이 아닌 B 직군으로 변경
>   
>   * 22기에서 이 회원이 B 직군으로 변경했다고 수정해주는 칸은 따로 없는 것 같다.
> * 기수에 대한 변경은 있으나, 특정 회원의 기수가 수정될 때 수정된 기수에 대한 직군 변경은 존재하지 않는 것 같음.
> 
> ### 임시로 내린 결론 및 개발상황
> 따라서 **GenerationMember의 `Position`, `SubPosition`을 nullable하게 변경하려 합니다.**

전에 제가 오프라인에서 한 번 질문했던 것 같은데, 제가 기억하는게 맞다면...
8기 정보가 존재하는 회원, 즉 위클리 서비스에 이미 계정이 존재하는 회원의 경우는 회원 수정 API가 아닌 회원 등록 API를 통해 22기 정보가 추가될 것 같아요.
즉, 회원 등록 API 요청시 이메일값을 기준으로 이미 존재하는 회원인지 판단하고 이미 존재한다면 새로운 Member를 추가해주는게 아닌 기존 Member에 GenerationMember를 추가해주는 방식이 될 것 같아요.

회원 수정 API로 다른 기수를 추가해주는 경우엔.. 가장 최근 직군 따라 가는게 좋지 않을까?라는 생각이 드는데(회원 정보 조회시에 가장 최근 직군을 보여주기 때문), 함께 얘기 나눠보면 좋을 것 같아요!

**Comment by xxeol2** [comment]
> 회원 정보 수정 시에 email도 변경이 가능한데, JwtTokenProviderTest를 보면 알 수 있듯이 사실상 이메일이 payload이자 식별자입니다. 이메일을 변경할 수 있게 하는 것이 맞을까요?

오.. 어렵다....
안내 메일을 받는 이메일 주소를 변경하고싶은 회원이 존재할 수도 있는데..
수정을 열어놓기엔 이메일을 식별자로 사용하고있고....
이것도 함께 얘기해볼 문제인 것 같아요

**Comment by kth990303** [comment]
@xxeol2 
> 전에 제가 오프라인에서 한 번 질문했던 것 같은데, 제가 기억하는게 맞다면...
8기 정보가 존재하는 회원, 즉 위클리 서비스에 이미 계정이 존재하는 회원의 경우는 회원 수정 API가 아닌 회원 등록 API를 통해 22기 정보가 추가될 것 같아요.
즉, 회원 등록 API 요청시 이메일값을 기준으로 이미 존재하는 회원인지 판단하고 이미 존재한다면 새로운 Member를 추가해주는게 아닌 기존 Member에 GenerationMember를 추가해주는 방식이 될 것 같아요.

그러네요 Member 생성으로 제가 한정지어서 생각했었나봐요.
Member가 있으면 거기에 GenerationMember를 추가하고 member의 generations 프로퍼티를 수정하든 값을 추가하든 하면 되겠네요 ㅎㅎ

---

> 저번 회의때 해당 부분에 대해서 이전 기수에 대해서도 전부 다 동일한 직군으로 넣어주기로 얘기 나왔던걸로 기억해요!

초기세팅을 마친 이후거나 아니면 23기 이후 회원들을 생성할 때는 문제가 없을 거 같긴 하네요. 회원 정보가 존재할테고, 거기에 기수회원 추가만 하면 되니!

근데 초기세팅이 안된 수료한 유저분들 정보를 생성할 때 `13기 안드로이드 -> 22기 백엔드`의 경우에 해당되는 회원을 한번에 단건 생성하면 `13기 백엔드, 22기 백엔드`로 삽입될 거 같은데 괜찮을까요? (13기 생성 한번, 22기 생성 한번처럼 따로따로 하면 괜찮겠지만)

회원 관리 페이지`에서 직군을 UI 상으로 띄워줄 때는 최근 직군만 보여주되, 특정 회원의 이전 기수에 활동했던 직군 정보까지 최근 직군과 동일하게 수정하는 부분은 얘기가 안나왔던 거 같았는데... 혹시 이 부분 얘기가 나왔었나요? 

---

> 문제 상황
특정 회원이 8기 정보만 있었는데 22기 정보가 추가됨.
그런데 22기에서 이 회원은 A 직군이 아닌 B 직군으로 변경
22기에서 이 회원이 B 직군으로 변경했다고 수정해주는 칸은 따로 없는 것 같다.
기수에 대한 변경은 있으나, 특정 회원의 기수가 수정될 때 수정된 기수에 대한 직군 변경은 존재하지 않는 것 같음.

조금 생각해보니 이 문제는 `직군 변경` 수정을 하면 해결될 것 같은 문제긴 하네요 ㅎㅎ

다만, 아래 경우는 여전히 문제가 될 거 같아요

ex) 14기 백엔드 - 21기 안드로이드 - 22기 IOS 
-> 회원 수정에서 15기, 22기로 바꿈  (15기인데 오타로 14기로 잘못 집어넣었던 상황이라 하죠)
-> 15기 null (또는 최근 직군인 IOS) - 22기 IOS 

해당 회원은 15기에 대한 기수회원 정보가 없으니 기수회원을 생성할 때 직군은 null 또는 최근 직군이 될 듯한데... 위와 동일한 문제긴 하네요.

**Comment by bugoverdose** [comment]
우리가 이전 기수 정보에 너무 집착하는건 아닌가라는 생각도 드네요. 이전 기수에서 개발자였는지, 디자이너였는지 등의 정보는 사실 운영진 입장에서 의미가 없지 않나? 싶기도 한디

**Comment by bugoverdose** [comment]
태현이와의 대화 내용 결론

우선은 기존에 계획한 그대로 회원 정보 저장. 기수 정보가 여러개인 경우, 이전 기수의 직군 등의 정보는 기본적으로 null로 저장. 

- name, gender, email 등은 같은 데이터로 저장.
- 직군, 세부직군의 경우 값이 이미 입력되었으면 그대로 활용, 그 외의 경우에는 null로 저장.

향후 단건 수정하거나, csv 파일로 저장할 때 null로 저장된 부분들 전부 덮어쓰는 방식으로 진행.

```
POST /api/members
Authorization: Bearer admin.jwt.token

RequestBody {
    name: string
    gender: string
    email: string
		phoneNumber: string
    generations: [int]
    position: string
    subPosition: string
    status: string
    isManager: boolean
}
```
